### ISSUE TITLE
Provide access to a test Kubernetes pod for further Nextflow/TESK testing

### ISSUE THREAD

**Issue by tskir** [CINECA-project/wp4-federated-joint-cohort-analysis#13]
The first round of problems with Nextflow/TESK were resolved in https://github.com/CINECA-project/wp4-federated-joint-cohort-analysis/issues/2.

To continue testing, I need access to a test Kubernetes pod which shares the file system with TESK pods, because it is a requrement when submitting jobs through Nextflow.

**Comment by shukapoo** [comment]
Details of how accessing Kubernetes cluster provided to Krill & Kaur. Once they have access, a common working pod could be setup.

**Comment by lvarin** [comment]
Could you try now with:
https://csc-tesk-cineca.c03.k8s-popup.csc.fi

Some things have changed since April

**Comment by tskir** [comment]
This is done, I can confirm I was able to successfully log into the working pod. I'm going to go ahead and close this issue
