### ISSUE TITLE
Install additional packages into the test Nextflow pod and commit pod's Dockerfile

### ISSUE THREAD

**Issue by tskir** [CINECA-project/wp4-federated-joint-cohort-analysis#17]
@lvarin @shukapoo I'm currently working on debugging #14, and to efficiently do that I need to be able to:
* Transfer files in and out of the pod
* Be able to run modified (non-stock) Nextflow versions
* Ideally, be able to build Nextflow from source directly from inside the pod

For that, I need to have at least these packages installed inside the text Nextflow pod:
* `rsync` (otherwise `oc rsync` falls back to copying every single file again, which is very slow)
* `git`
* `make`
* `tput`

In the future this list might grow. I think it might be a good idea to commit the `Dockerfile` which you use to create the test pods, so that it could be directly amended and contain the full list of dependencies

**Comment by lvarin** [comment]
Hello,
The Docker file is one of my personal repositories:

https://github.com/lvarin/nextflow-tes-okd/blob/master/Dockerfile

I will add your dependencies to it. 

Regards

**Comment by lvarin** [comment]
The new container is deployed in Openshift's pod `nextflow-dockerhub-8-q69bb`

**Comment by tskir** [comment]
This is quite an old ticket, but I've verified all dependencies are now installed, so will close it
