### ISSUE TITLE
Update Nextflow version & include openjdk8

### ISSUE THREAD

**Issue by tskir** [CINECA-project/wp4-federated-joint-cohort-analysis#36]
Hi @lvarin, once you have time could you please update [the Nextflow pod image](https://github.com/lvarin/nextflow-tes-okd/blob/master/Dockerfile):
* To include the latest Nextflow version (21.01.0-edge currently)
* And to also install the `openjdk8` package, it seems to be the last dependency to be able to compile Nextflow directly in the pod

**Comment by lvarin** [comment]
Done:

  https://github.com/lvarin/nextflow-tes-okd/pull/new/21.01.0-edge

and:

  https://hub.docker.com/r/lvarin/nextflow-tes-okd/tags

**Comment by tskir** [comment]
Thank you for the quick action @lvarin. I can confirm that the new image is capable of building Nextflow from source (hooray!) However, for some bizarre reason, the system-wide Nextflow version is still some old one:

```bash
$ sudo docker run lvarin/nextflow-tes-okd:21.01.0-edge nextflow -v
nextflow version 20.07.1.5414
```

Whereas if I run the source image everything seems to work:

```bash
$ sudo docker run nextflow/nextflow:21.01.0-edge nextflow -v
nextflow version 21.01.0-edge.5476
```

**Comment by lvarin** [comment]
I am checking it. The problem comes from the way the submodule is used. I am building it now using a workaround approach, but will coma back to this and make a proper `Makefile`.

**Comment by lvarin** [comment]
It is fixed now:
```
$ docker run --rm lvarin/nextflow-tes-okd:21.01.0-edge nextflow -v
Unable to find image 'lvarin/nextflow-tes-okd:21.01.0-edge' locally
Trying to pull repository docker.io/lvarin/nextflow-tes-okd ... 
21.01.0-edge: Pulling from docker.io/lvarin/nextflow-tes-okd
e7c96db7181b: Already exists 
f910a506b6cb: Already exists 
b6abafe80f63: Already exists 
103c7ee30fca: Already exists 
9c86dc1c7d0c: Already exists 
fff2ff989b23: Already exists 
98f0e8fa3dc7: Already exists 
5a72e13b3900: Already exists 
86a65520d024: Already exists 
cd69af5701a1: Already exists 
d2c5d6a57ace: Already exists 
90b003201e69: Already exists 
6e7fd9e1e4ea: Pull complete 
e09e5c27f922: Pull complete 
Digest: sha256:ba7ba698164346b64991eff36efbb4ddd974320d60fadfff279bfc54c97278fe
Status: Downloaded newer image for docker.io/lvarin/nextflow-tes-okd:21.01.0-edge
nextflow version 21.01.0-edge.5477
```

**Comment by tskir** [comment]
Can confirm everything's good now, closing this issue
