### ISSUE TITLE
Document scope, pipeline & user story for Task 4.2

### ISSUE THREAD

**Issue by shukapoo** [CINECA-project/wp4-federated-joint-cohort-analysis#6]

**Comment by shukapoo** [comment]
1st version of document initiated: https://github.com/CINECA-project/wp4-federated-joint-cohort-analysis/blob/master/Deliverable4.2.md

**Comment by shukapoo** [comment]
Project directory reorganised, document moved to: https://github.com/CINECA-project/wp4-federated-joint-cohort-analysis/tree/master/docs/4.2-technical-framework

**Comment by shukapoo** [comment]
Updated document as per @elisa's review comments

**Comment by tskir** [comment]
Changes from Google Docs were reintroduced by @lvarin in 37, so this can be safely closed
